// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdnpaJLjZkRZqo6qI-235JScta4RtadPQ',
    appId: '1:103035198429:web:509ffd75a9fb7f12263434',
    messagingSenderId: '103035198429',
    projectId: 'appdev-final-e0abb',
    authDomain: 'appdev-final-e0abb.firebaseapp.com',
    storageBucket: 'appdev-final-e0abb.firebasestorage.app',
    measurementId: 'G-HDL7HVPJS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVgcIJm_TefarheWyv7TotYoX-Rilgt40',
    appId: '1:103035198429:android:d531749bc0b3017b263434',
    messagingSenderId: '103035198429',
    projectId: 'appdev-final-e0abb',
    storageBucket: 'appdev-final-e0abb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcIqMV5Q45ORAZ_f8TqJFKTp3ZEk6vkg8',
    appId: '1:103035198429:ios:9ab125536babb34c263434',
    messagingSenderId: '103035198429',
    projectId: 'appdev-final-e0abb',
    storageBucket: 'appdev-final-e0abb.firebasestorage.app',
    iosBundleId: 'com.example.appdevFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcIqMV5Q45ORAZ_f8TqJFKTp3ZEk6vkg8',
    appId: '1:103035198429:ios:9ab125536babb34c263434',
    messagingSenderId: '103035198429',
    projectId: 'appdev-final-e0abb',
    storageBucket: 'appdev-final-e0abb.firebasestorage.app',
    iosBundleId: 'com.example.appdevFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdnpaJLjZkRZqo6qI-235JScta4RtadPQ',
    appId: '1:103035198429:web:d619a68a1fd2a1ae263434',
    messagingSenderId: '103035198429',
    projectId: 'appdev-final-e0abb',
    authDomain: 'appdev-final-e0abb.firebaseapp.com',
    storageBucket: 'appdev-final-e0abb.firebasestorage.app',
    measurementId: 'G-7DENK9CH0Z',
  );
}
